version: '2'
services:
  nginx:
    image: nginx:1.29.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - blog-app-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - blog-app-network
  
  site:
    build: .
    ports:
      - "3000"
    networks:
      - blog-app-network

networks:
  - blog-app-network
